### PR TITLE
upgrade mssql driver

### PR DESCRIPTION
**Pull request by laglangyue**
cherry pick
https://github.com/apache/pekko-persistence-jdbc/pull/161/files

### CODE REVIEW

**Comment by laglangyue** [comment]
I know why it failed, the test code is a bit difficult, and the jdbc url is not configurable. I need some time to understand how to add the params to url

**Comment by laglangyue** [comment]
@pjfanning cc

**Comment by laglangyue** [comment]
image


`org.apache.pekko.projection.kafka.internal.KafkaSourceProviderImplSpec`

This error seems to be frequent in CI, do you know the reason? @pjfanning

**Comment by laglangyue** [comment]
test `KafkaSourceProviderImplSpec` ok in my pc, but failed in CI

**Review by pjfanning — APPROVED** [review]
lgtm - thanks

**Comment by raboof** [comment]
> image
> 
> `org.apache.pekko.projection.kafka.internal.KafkaSourceProviderImplSpec`
> 
> This error seems to be frequent in CI, do you know the reason? @pjfanning

this is a known flaky test (#103). IMHO we should link to flaky tests when we encounter them (to be able to more easily see which flaky tests are in particular need of fixing), and we should re-run the tests until they are green before merging (to avoid accidentally merging with legitimate errors)

**Pull request merged**
